--[[solution to Problem 2 from projecteuler.net

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    
    By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    find the sum of the even-valued terms.
    --]]

-- step1 generate fibonacci sequence in array
-- INPUT: n is limit
function genFib(limit)
  fib={1,1}
  local i=3
  while i<limit do
    fib[i]=fib[i-1]+fib[i-2]
    if fib[i] > limit then
      table.remove(fib,i)
      break
    end
    i=i+1
  end
  return fib
end

local result=genFib(100)
for i=1,#result do
  io.write(result[i]," ")
end
io.write("\n")

function main()
  local lim=4000000
  local f=genFib(lim)
  --now filter out the even fibs and add them up as you go
  local total=0
  for i=1,#f do
    if f[i] %2 == 0 then
      total=total+f[i]
    end
  end
  print("the total sum is ", total)
end

main()